REFIND:
    retriever: HybridRetriever
    input_prompt_template: REFIND_PROMPT_TEMPLATE
    threshold_list: [0.1, 0.2, 0.3, 0.4]
FAVA:
    retriever: HybridRetriever

Retriever:
    language: es
    input_file_path: retriever/es_wiki_corpus.jsonl
    parameters:
        retrieval_chunk_size: 600
        retrieval_chunk_overlap: 30
        retrieval_top_k: 5
HybridRetriever:
    language: es
    input_file_path: retriever/es_wiki_corpus.jsonl
    embedding_model_path: intfloat/multilingual-e5-large
    parameters:
        retrieval_chunk_size: 600
        retrieval_chunk_overlap: 30
        retrieval_top_k: 10
        reranking_top_k: 5